    version: '3.6'
    services:
        db:
            image: mysql:5.7
            volumes:
                - ./reservasi:/docker-entrypoint-initdb.d
                - dbdata:/var/lib/mysql
            restart: always
            environment:
                MYSQL_ROOT_PASSWORD: buayakecil
                MYSQL_DATABASE: reservasi
                MYSQL_USER: userawan
                MYSQL_PASSWORD: buayakecil

        worker:
            image: reserve
            depends_on:
                - db
            environment:
                DB_HOST: db
                DB_USERNAME: userawan
                DB_PASSWORD: buayakecil
                DB_NAME: reservasi

        nginx:
            image: nginx:stable-alpine
            ports:
                - 1234:80
            depends_on:
                - worker
            volumes:
                - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    volumes:
        dbdata:
